Repository buildarr/buildarr-radarr, pull requests merged in 2024-03, with the labels that each got.

#51 Update Poetry and lock file
  .github/workflows/release.yml
  .pre-commit-config.yaml
  poetry.lock
  requirements.txt
Labels: bug, pipeline

#47 Add missing preferred size quality definition
  buildarr_radarr/config/settings/quality.py
Labels: bug, good first issue

#53 Make auth optional for qBittorrent download clients
  buildarr_radarr/config/settings/download_clients/torrent/qbittorrent.py
Labels: bug

#55 Tag v0.2.5
  docs/release-notes.md
  pyproject.toml
Labels: release
